const data = {
  queryCost: 1,
  latitude: 51.5072,
  longitude: -0.1275,
  resolvedAddress: "london",
  address: "london",
  timezone: "Europe/London",
  tzoffset: 0,
  days: [
    {
      datetime: "2026-03-09",
      datetimeEpoch: 1773014400,
      tempmax: 59.4,
      tempmin: 43.6,
      temp: 50.7,
      feelslikemax: 59.4,
      feelslikemin: 43.6,
      feelslike: 50.5,
      dew: 46.1,
      humidity: 85.1,
      precip: 0.056,
      precipprob: 41.9,
      precipcover: 16.67,
      preciptype: ["rain"],
      snow: 0,
      snowdepth: 0,
      windgust: 15.4,
      windspeed: 5.4,
      winddir: 179.4,
      pressure: 1018.8,
      cloudcover: 82,
      visibility: 13.2,
      solarradiation: 150.3,
      solarenergy: 12.9,
      uvindex: 5,
      severerisk: 10,
      sunrise: "06:28:15",
      sunriseEpoch: 1773037695,
      sunset: "17:54:50",
      sunsetEpoch: 1773078890,
      moonphase: 0.69,
      conditions: "Partially cloudy",
      description: "Partly cloudy throughout the day.",
      icon: "partly-cloudy-day",
      stations: ["EGWU", "EGLL", "D5621", "EGLC"],
      source: "comb",
      hours: [
        {
          datetime: "00:00:00",
          datetimeEpoch: 1773014400,
          temp: 46.3,
          feelslike: 44.5,
          humidity: 92.25,
          dew: 44.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.8,
          windspeed: 4.1,
          winddir: 146,
          pressure: 1021,
          visibility: 3.3,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["EGWU", "EGLL", "D5621", "EGLC"],
          source: "obs",
        },
        {
          datetime: "01:00:00",
          datetimeEpoch: 1773018000,
          temp: 46.3,
          feelslike: 44.5,
          humidity: 92.25,
          dew: 44.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.2,
          windspeed: 4.2,
          winddir: 133,
          pressure: 1021,
          visibility: 3.3,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["EGWU", "EGLL", "D5621", "EGLC"],
          source: "obs",
        },
        {
          datetime: "02:00:00",
          datetimeEpoch: 1773021600,
          temp: 45.2,
          feelslike: 45.2,
          humidity: 94.02,
          dew: 43.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.2,
          windspeed: 2.7,
          winddir: 134.8,
          pressure: 1021,
          visibility: 15,
          cloudcover: 88.9,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "03:00:00",
          datetimeEpoch: 1773025200,
          temp: 44.7,
          feelslike: 44.7,
          humidity: 92.07,
          dew: 42.5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 6.5,
          windspeed: 2.2,
          winddir: 131.1,
          pressure: 1020,
          visibility: 15,
          cloudcover: 85,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "04:00:00",
          datetimeEpoch: 1773028800,
          temp: 44.1,
          feelslike: 44.1,
          humidity: 91.42,
          dew: 41.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.1,
          windspeed: 1.8,
          winddir: 112.7,
          pressure: 1020,
          visibility: 15,
          cloudcover: 79.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "05:00:00",
          datetimeEpoch: 1773032400,
          temp: 43.6,
          feelslike: 43.6,
          humidity: 92.68,
          dew: 41.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.1,
          windspeed: 0.9,
          winddir: 88.2,
          pressure: 1020,
          visibility: 15,
          cloudcover: 85.4,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "06:00:00",
          datetimeEpoch: 1773036000,
          temp: 43.6,
          feelslike: 43.6,
          humidity: 92.68,
          dew: 41.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.2,
          windspeed: 1.3,
          winddir: 52.4,
          pressure: 1020,
          visibility: 15,
          cloudcover: 92.5,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "07:00:00",
          datetimeEpoch: 1773039600,
          temp: 43.8,
          feelslike: 43.8,
          humidity: 93.98,
          dew: 42.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.6,
          windspeed: 1.8,
          winddir: 39.3,
          pressure: 1020,
          visibility: 15,
          cloudcover: 100,
          solarradiation: 6,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "08:00:00",
          datetimeEpoch: 1773043200,
          temp: 44.7,
          feelslike: 44.7,
          humidity: 91.44,
          dew: 42.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.5,
          windspeed: 1.8,
          winddir: 69.3,
          pressure: 1020,
          visibility: 15,
          cloudcover: 100,
          solarradiation: 95,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "09:00:00",
          datetimeEpoch: 1773046800,
          temp: 46.1,
          feelslike: 46.1,
          humidity: 89.62,
          dew: 43.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.1,
          windspeed: 2.2,
          winddir: 88.7,
          pressure: 1020,
          visibility: 15,
          cloudcover: 97.5,
          solarradiation: 240,
          solarenergy: 0.9,
          uvindex: 2,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "10:00:00",
          datetimeEpoch: 1773050400,
          temp: 48.6,
          feelslike: 48.6,
          humidity: 86.13,
          dew: 44.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.4,
          windspeed: 1.8,
          winddir: 96.5,
          pressure: 1020,
          visibility: 15,
          cloudcover: 95.2,
          solarradiation: 373,
          solarenergy: 1.3,
          uvindex: 4,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "11:00:00",
          datetimeEpoch: 1773054000,
          temp: 53.1,
          feelslike: 53.1,
          humidity: 78.59,
          dew: 46.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.6,
          windspeed: 3.1,
          winddir: 206.8,
          pressure: 1020,
          visibility: 15,
          cloudcover: 93,
          solarradiation: 474,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "12:00:00",
          datetimeEpoch: 1773057600,
          temp: 56.4,
          feelslike: 56.4,
          humidity: 71.28,
          dew: 47.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11,
          windspeed: 4.7,
          winddir: 211.6,
          pressure: 1019,
          visibility: 15,
          cloudcover: 82.3,
          solarradiation: 531,
          solarenergy: 1.9,
          uvindex: 5,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "13:00:00",
          datetimeEpoch: 1773061200,
          temp: 58.6,
          feelslike: 58.6,
          humidity: 65.06,
          dew: 46.8,
          precip: 0,
          precipprob: 41.9,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.6,
          windspeed: 4.5,
          winddir: 222.1,
          pressure: 1018,
          visibility: 13.9,
          cloudcover: 71.8,
          solarradiation: 535,
          solarenergy: 1.9,
          uvindex: 5,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "14:00:00",
          datetimeEpoch: 1773064800,
          temp: 59.4,
          feelslike: 59.4,
          humidity: 62.58,
          dew: 46.7,
          precip: 0,
          precipprob: 41.9,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.8,
          windspeed: 5.4,
          winddir: 234.9,
          pressure: 1018,
          visibility: 13.7,
          cloudcover: 77.4,
          solarradiation: 469,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "15:00:00",
          datetimeEpoch: 1773068400,
          temp: 59.4,
          feelslike: 59.4,
          humidity: 63.86,
          dew: 47.2,
          precip: 0,
          precipprob: 41.9,
          snow: 0,
          snowdepth: 0,
          preciptype: ["rain"],
          windgust: 15.4,
          windspeed: 4.3,
          winddir: 231.7,
          pressure: 1017,
          visibility: 6.8,
          cloudcover: 70.7,
          solarradiation: 409,
          solarenergy: 1.5,
          uvindex: 4,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "16:00:00",
          datetimeEpoch: 1773072000,
          temp: 59.1,
          feelslike: 59.1,
          humidity: 66.02,
          dew: 47.7,
          precip: 0,
          precipprob: 41.9,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.8,
          windspeed: 4,
          winddir: 222.9,
          pressure: 1017,
          visibility: 13.3,
          cloudcover: 33.3,
          solarradiation: 295,
          solarenergy: 1.1,
          uvindex: 3,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "17:00:00",
          datetimeEpoch: 1773075600,
          temp: 58,
          feelslike: 58,
          humidity: 70.97,
          dew: 48.6,
          precip: 0,
          precipprob: 41.9,
          snow: 0,
          snowdepth: 0,
          preciptype: ["rain"],
          windgust: 9.6,
          windspeed: 3.4,
          winddir: 195.6,
          pressure: 1017,
          visibility: 7.6,
          cloudcover: 29.3,
          solarradiation: 152,
          solarenergy: 0.5,
          uvindex: 2,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "18:00:00",
          datetimeEpoch: 1773079200,
          temp: 55.5,
          feelslike: 55.5,
          humidity: 82.56,
          dew: 50.3,
          precip: 0,
          precipprob: 41.9,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.2,
          windspeed: 2.5,
          winddir: 180.1,
          pressure: 1017,
          visibility: 14.9,
          cloudcover: 50.8,
          solarradiation: 27,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "19:00:00",
          datetimeEpoch: 1773082800,
          temp: 53.3,
          feelslike: 53.3,
          humidity: 91.75,
          dew: 51,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.5,
          windspeed: 2.5,
          winddir: 191.6,
          pressure: 1017,
          visibility: 15,
          cloudcover: 84.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "20:00:00",
          datetimeEpoch: 1773086400,
          temp: 52.4,
          feelslike: 52.4,
          humidity: 95.46,
          dew: 51.2,
          precip: 0.008,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ["rain"],
          windgust: 9.8,
          windspeed: 2.5,
          winddir: 171,
          pressure: 1017,
          visibility: 15,
          cloudcover: 86.5,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "21:00:00",
          datetimeEpoch: 1773090000,
          temp: 51.9,
          feelslike: 51.9,
          humidity: 95.45,
          dew: 50.6,
          precip: 0.012,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ["rain"],
          windgust: 6.3,
          windspeed: 2.2,
          winddir: 158.7,
          pressure: 1017,
          visibility: 15,
          cloudcover: 82.3,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "22:00:00",
          datetimeEpoch: 1773093600,
          temp: 51.2,
          feelslike: 51.2,
          humidity: 95.44,
          dew: 49.9,
          precip: 0.016,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ["rain"],
          windgust: 4.7,
          windspeed: 2,
          winddir: 185.4,
          pressure: 1017,
          visibility: 15,
          cloudcover: 86.3,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: null,
          source: "fcst",
        },
        {
          datetime: "23:00:00",
          datetimeEpoch: 1773097200,
          temp: 50.6,
          feelslike: 50.6,
          humidity: 95.42,
          dew: 49.4,
          precip: 0.02,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ["rain"],
          windgust: 6,
          windspeed: 2.9,
          winddir: 201.8,
          pressure: 1017,
          visibility: 15,
          cloudcover: 95.7,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Overcast",
          icon: "cloudy",
          stations: null,
          source: "fcst",
        },
      ],
    },
  ],
  alerts: [],
  stations: {
    EGWU: {
      distance: 20810,
      latitude: 51.55,
      longitude: -0.42,
      useCount: 0,
      id: "EGWU",
      name: "EGWU",
      quality: 50,
      contribution: 0,
    },
    EGLC: {
      distance: 12326,
      latitude: 51.5,
      longitude: 0.05,
      useCount: 0,
      id: "EGLC",
      name: "EGLC",
      quality: 50,
      contribution: 0,
    },
    EGLL: {
      distance: 22556,
      latitude: 51.48,
      longitude: -0.45,
      useCount: 0,
      id: "EGLL",
      name: "EGLL",
      quality: 50,
      contribution: 0,
    },
    D5621: {
      distance: 11186,
      latitude: 51.535,
      longitude: 0.028,
      useCount: 0,
      id: "D5621",
      name: "DW5621 Upton Park UK",
      quality: 0,
      contribution: 0,
    },
  },
};

export { data };
